pipeline:
  identifier: Build_mrakbg_KINGGOD_1741764335123
  name: Dockerpush-Anuj
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: mrakbg/KINGGOD
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    shell: Sh
                    command: npm run test || true
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: Dockerconnector
                    repo: mrakbg/world
                    tags:
                      - latest
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: |-
                      docker run -d --name test-container -p 3000:3000 mrakbg/world:latest
                      sleep 5
                      curl -f http://localhost:3000
                  description: testing
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
  tags: {}
